/// Dados de localização do Brasil (Estados e principais cidades)
class BrazilLocationsData {
  /// Lista de estados brasileiros
  static const List<String> states = [
    'Acre',
    'Alagoas',
    'Amapá',
    'Amazonas',
    'Bahia',
    'Ceará',
    'Distrito Federal',
    'Espírito Santo',
    'Goiás',
    'Maranhão',
    'Mato Grosso',
    'Mato Grosso do Sul',
    'Minas Gerais',
    'Pará',
    'Paraíba',
    'Paraná',
    'Pernambuco',
    'Piauí',
    'Rio de Janeiro',
    'Rio Grande do Norte',
    'Rio Grande do Sul',
    'Rondônia',
    'Roraima',
    'Santa Catarina',
    'São Paulo',
    'Sergipe',
    'Tocantins',
  ];

  /// Mapa de cidades por estado (principais cidades)
  static const Map<String, List<String>> citiesByState = {
    'São Paulo': [
      'São Paulo',
      'Campinas',
      'Santos',
      'São José dos Campos',
      'Ribeirão Preto',
      'Sorocaba',
      'São José do Rio Preto',
      'Piracicaba',
      'Bauru',
      'Birigui',
      'Araçatuba',
      'Presidente Prudente',
      'Marília',
      'Araraquara',
      'Franca',
    ],
    'Rio de Janeiro': [
      'Rio de Janeiro',
      'Niterói',
      'Duque de Caxias',
      'Nova Iguaçu',
      'São Gonçalo',
      'Campos dos Goytacazes',
      'Petrópolis',
      'Volta Redonda',
    ],
    'Minas Gerais': [
      'Belo Horizonte',
      'Uberlândia',
      'Contagem',
      'Juiz de Fora',
      'Betim',
      'Montes Claros',
      'Ribeirão das Neves',
      'Uberaba',
    ],
    'Bahia': [
      'Salvador',
      'Feira de Santana',
      'Vitória da Conquista',
      'Camaçari',
      'Itabuna',
      'Juazeiro',
      'Lauro de Freitas',
    ],
    'Paraná': [
      'Curitiba',
      'Londrina',
      'Maringá',
      'Ponta Grossa',
      'Cascavel',
      'São José dos Pinhais',
      'Foz do Iguaçu',
    ],
    'Rio Grande do Sul': [
      'Porto Alegre',
      'Caxias do Sul',
      'Pelotas',
      'Canoas',
      'Santa Maria',
      'Gravataí',
      'Novo Hamburgo',
    ],
    'Pernambuco': [
      'Recife',
      'Jaboatão dos Guararapes',
      'Olinda',
      'Caruaru',
      'Petrolina',
      'Paulista',
    ],
    'Ceará': [
      'Fortaleza',
      'Caucaia',
      'Juazeiro do Norte',
      'Maracanaú',
      'Sobral',
    ],
    'Pará': [
      'Belém',
      'Ananindeua',
      'Santarém',
      'Marabá',
      'Castanhal',
    ],
    'Santa Catarina': [
      'Florianópolis',
      'Joinville',
      'Blumenau',
      'São José',
      'Criciúma',
      'Chapecó',
    ],
    'Goiás': [
      'Goiânia',
      'Aparecida de Goiânia',
      'Anápolis',
      'Rio Verde',
      'Luziânia',
    ],
    'Maranhão': [
      'São Luís',
      'Imperatriz',
      'São José de Ribamar',
      'Timon',
      'Caxias',
    ],
    'Paraíba': [
      'João Pessoa',
      'Campina Grande',
      'Santa Rita',
      'Patos',
    ],
    'Espírito Santo': [
      'Vitória',
      'Vila Velha',
      'Serra',
      'Cariacica',
      'Cachoeiro de Itapemirim',
    ],
    'Amazonas': [
      'Manaus',
      'Parintins',
      'Itacoatiara',
      'Manacapuru',
    ],
    'Mato Grosso': [
      'Cuiabá',
      'Várzea Grande',
      'Rondonópolis',
      'Sinop',
    ],
    'Rio Grande do Norte': [
      'Natal',
      'Mossoró',
      'Parnamirim',
      'São Gonçalo do Amarante',
    ],
    'Piauí': [
      'Teresina',
      'Parnaíba',
      'Picos',
      'Floriano',
    ],
    'Alagoas': [
      'Maceió',
      'Arapiraca',
      'Rio Largo',
      'Palmeira dos Índios',
    ],
    'Distrito Federal': [
      'Brasília',
    ],
    'Mato Grosso do Sul': [
      'Campo Grande',
      'Dourados',
      'Três Lagoas',
      'Corumbá',
    ],
    'Sergipe': [
      'Aracaju',
      'Nossa Senhora do Socorro',
      'Lagarto',
      'Itabaiana',
    ],
    'Rondônia': [
      'Porto Velho',
      'Ji-Paraná',
      'Ariquemes',
      'Vilhena',
    ],
    'Tocantins': [
      'Palmas',
      'Araguaína',
      'Gurupi',
      'Porto Nacional',
    ],
    'Acre': [
      'Rio Branco',
      'Cruzeiro do Sul',
      'Sena Madureira',
    ],
    'Amapá': [
      'Macapá',
      'Santana',
      'Laranjal do Jari',
    ],
    'Roraima': [
      'Boa Vista',
      'Rorainópolis',
      'Caracaraí',
    ],
  };

  /// Mapa de siglas dos estados brasileiros
  static const Map<String, String> stateAbbreviations = {
    'Acre': 'AC',
    'Alagoas': 'AL',
    'Amapá': 'AP',
    'Amazonas': 'AM',
    'Bahia': 'BA',
    'Ceará': 'CE',
    'Distrito Federal': 'DF',
    'Espírito Santo': 'ES',
    'Goiás': 'GO',
    'Maranhão': 'MA',
    'Mato Grosso': 'MT',
    'Mato Grosso do Sul': 'MS',
    'Minas Gerais': 'MG',
    'Pará': 'PA',
    'Paraíba': 'PB',
    'Paraná': 'PR',
    'Pernambuco': 'PE',
    'Piauí': 'PI',
    'Rio de Janeiro': 'RJ',
    'Rio Grande do Norte': 'RN',
    'Rio Grande do Sul': 'RS',
    'Rondônia': 'RO',
    'Roraima': 'RR',
    'Santa Catarina': 'SC',
    'São Paulo': 'SP',
    'Sergipe': 'SE',
    'Tocantins': 'TO',
  };

  /// Retorna as cidades de um estado
  static List<String> getCitiesForState(String state) {
    return citiesByState[state] ?? [];
  }

  /// Retorna a sigla de um estado
  static String? getStateAbbreviation(String state) {
    return stateAbbreviations[state];
  }
}
