/// Dados de localização dos Estados Unidos (Estados e principais cidades)
class USALocationsData {
  /// Lista de estados americanos
  static const List<String> states = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
  ];

  /// Mapa de siglas dos estados
  static const Map<String, String> stateAbbreviations = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
  };

  /// Mapa de cidades por estado (principais cidades)
  static const Map<String, List<String>> citiesByState = {
    'California': [
      'Los Angeles',
      'San Francisco',
      'San Diego',
      'San Jose',
      'Sacramento',
      'Fresno',
      'Oakland',
      'Long Beach',
    ],
    'Texas': [
      'Houston',
      'Dallas',
      'Austin',
      'San Antonio',
      'Fort Worth',
      'El Paso',
      'Arlington',
    ],
    'Florida': [
      'Miami',
      'Orlando',
      'Tampa',
      'Jacksonville',
      'Fort Lauderdale',
      'Tallahassee',
    ],
    'New York': [
      'New York City',
      'Buffalo',
      'Rochester',
      'Albany',
      'Syracuse',
    ],
    'Pennsylvania': [
      'Philadelphia',
      'Pittsburgh',
      'Harrisburg',
      'Allentown',
    ],
    'Illinois': [
      'Chicago',
      'Springfield',
      'Naperville',
      'Rockford',
    ],
    'Ohio': [
      'Columbus',
      'Cleveland',
      'Cincinnati',
      'Toledo',
    ],
    'Georgia': [
      'Atlanta',
      'Augusta',
      'Savannah',
      'Athens',
    ],
    'North Carolina': [
      'Charlotte',
      'Raleigh',
      'Greensboro',
      'Durham',
    ],
    'Michigan': [
      'Detroit',
      'Grand Rapids',
      'Lansing',
      'Ann Arbor',
    ],
    'New Jersey': [
      'Newark',
      'Jersey City',
      'Trenton',
      'Atlantic City',
    ],
    'Virginia': [
      'Virginia Beach',
      'Norfolk',
      'Richmond',
      'Arlington',
    ],
    'Washington': [
      'Seattle',
      'Spokane',
      'Tacoma',
      'Olympia',
    ],
    'Arizona': [
      'Phoenix',
      'Tucson',
      'Mesa',
      'Scottsdale',
    ],
    'Massachusetts': [
      'Boston',
      'Worcester',
      'Springfield',
      'Cambridge',
    ],
    'Tennessee': [
      'Nashville',
      'Memphis',
      'Knoxville',
      'Chattanooga',
    ],
    'Indiana': [
      'Indianapolis',
      'Fort Wayne',
      'Evansville',
    ],
    'Missouri': [
      'Kansas City',
      'St. Louis',
      'Springfield',
      'Columbia',
    ],
    'Maryland': [
      'Baltimore',
      'Annapolis',
      'Frederick',
    ],
    'Wisconsin': [
      'Milwaukee',
      'Madison',
      'Green Bay',
    ],
    'Colorado': [
      'Denver',
      'Colorado Springs',
      'Aurora',
      'Boulder',
    ],
    'Minnesota': [
      'Minneapolis',
      'St. Paul',
      'Rochester',
    ],
    'South Carolina': [
      'Charleston',
      'Columbia',
      'Greenville',
    ],
    'Alabama': [
      'Birmingham',
      'Montgomery',
      'Mobile',
    ],
    'Louisiana': [
      'New Orleans',
      'Baton Rouge',
      'Shreveport',
    ],
    'Kentucky': [
      'Louisville',
      'Lexington',
      'Frankfort',
    ],
    'Oregon': [
      'Portland',
      'Salem',
      'Eugene',
    ],
    'Oklahoma': [
      'Oklahoma City',
      'Tulsa',
      'Norman',
    ],
    'Connecticut': [
      'Hartford',
      'New Haven',
      'Stamford',
    ],
    'Utah': [
      'Salt Lake City',
      'Provo',
      'West Valley City',
    ],
    'Iowa': [
      'Des Moines',
      'Cedar Rapids',
      'Davenport',
    ],
    'Nevada': [
      'Las Vegas',
      'Reno',
      'Henderson',
    ],
    'Arkansas': [
      'Little Rock',
      'Fort Smith',
      'Fayetteville',
    ],
    'Kansas': [
      'Wichita',
      'Overland Park',
      'Kansas City',
    ],
    'New Mexico': [
      'Albuquerque',
      'Santa Fe',
      'Las Cruces',
    ],
    'Nebraska': [
      'Omaha',
      'Lincoln',
      'Bellevue',
    ],
    'West Virginia': [
      'Charleston',
      'Huntington',
      'Morgantown',
    ],
    'Idaho': [
      'Boise',
      'Meridian',
      'Nampa',
    ],
    'Hawaii': [
      'Honolulu',
      'Hilo',
      'Kailua',
    ],
    'New Hampshire': [
      'Manchester',
      'Nashua',
      'Concord',
    ],
    'Maine': [
      'Portland',
      'Lewiston',
      'Bangor',
    ],
    'Montana': [
      'Billings',
      'Missoula',
      'Great Falls',
    ],
    'Rhode Island': [
      'Providence',
      'Warwick',
      'Cranston',
    ],
    'Delaware': [
      'Wilmington',
      'Dover',
      'Newark',
    ],
    'South Dakota': [
      'Sioux Falls',
      'Rapid City',
      'Aberdeen',
    ],
    'North Dakota': [
      'Fargo',
      'Bismarck',
      'Grand Forks',
    ],
    'Alaska': [
      'Anchorage',
      'Fairbanks',
      'Juneau',
    ],
    'Vermont': [
      'Burlington',
      'Montpelier',
      'Rutland',
    ],
    'Wyoming': [
      'Cheyenne',
      'Casper',
      'Laramie',
    ],
  };

  /// Retorna as cidades de um estado
  static List<String> getCitiesForState(String state) {
    return citiesByState[state] ?? [];
  }
  
  /// Retorna a sigla de um estado
  static String? getStateAbbreviation(String state) {
    return stateAbbreviations[state];
  }
}
